// Generated placeholder for Firebase options. Replace the placeholder values
// below with your actual Firebase project configuration. This file is a
// minimal substitute for the firebase_options.dart normally generated by
// `flutterfire configure`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:android:000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_API_KEY',
    appId: '1:000000000000:ios:000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAY96YjG0s5V_oXmawNxuB_Cyk3dXafbbk",
      authDomain: "facturas-cbddc.firebaseapp.com",
      projectId: "facturas-cbddc",
      storageBucket: "facturas-cbddc.firebasestorage.app",
      messagingSenderId: "142274543659",
      appId: "1:142274543659:web:f1e969d2f2dc18d7fd2a6e",
      measurementId: "G-R4XDV1FGMV"
  );
}
